[package]
name = "termtris"
version = "0.1.1"
edition = "2021"

[dependencies]
crossterm = "0.27"
rand = "0.8"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
